// packages/vue/src/components/form/FormRenderer.vue
<template>
  <form class="mvs-form" @submit.prevent="handleSubmit">
    <div v-if="!runtime.isInitialized.value" class="mvs-form__loading">Loading...</div>
    <div v-else-if="runtime.error.value" class="mvs-form__error">
      {{ 'message' in runtime.error.value ? runtime.error.value.message : runtime.error.value.type }}
    </div>
    <template v-else>
      <slot name="header" :tree="semanticTree" />
      <div v-if="semanticTree?.headerActions?.length" class="mvs-actions mvs-actions--header">
        <button v-for="action in semanticTree.headerActions" :key="action.id" type="button" @click="handleAction(action)">
          {{ action.label }}
        </button>
      </div>
      <SectionRenderer
        v-for="section in semanticTree?.sections ?? []"
        :key="section.id"
        :section="section"
        :readonly="readonly"
        :onChange="(fieldId, value) => runtime.setFieldValue(fieldId, value)"
        :live-validators="liveValidators"
      >
        <template #field="slotProps">
          <slot name="field" v-bind="slotProps" />
        </template>
      </SectionRenderer>
      <slot name="footer" :tree="semanticTree">
        <footer class="mvs-form__footer">
          <button type="submit" class="mvs-button mvs-button--primary" :disabled="!runtime.isValid.value || runtime.isSubmitting.value">
            Submit
          </button>
          <div v-if="semanticTree?.footerActions?.length" class="mvs-actions mvs-actions--footer">
            <button v-for="action in semanticTree.footerActions" :key="action.id" type="button" @click="handleAction(action)">
              {{ action.label }}
            </button>
          </div>
        </footer>
      </slot>
      <div v-if="missingRenderers.length" class="mvs-warning">
        Missing renderers for: {{ missingRenderers.join(', ') }}
      </div>
    </template>
  </form>
</template>

<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import type { FormViewSchema, EntitySchema } from '@manifesto-ai/schema'
import type {
  EvaluationContext,
  FetchHandler,
  NavigateHandler,
  EmitHandler,
  FormRuntime,
  FormRuntimeError,
} from '@manifesto-ai/engine'
import {
  resolveFieldRenderers,
  type ResolvedFormSemanticNode,
  type SemanticRendererRegistry,
  type LightweightValidator,
  type ActionSemanticNode,
} from '@manifesto-ai/ui'
import type { FieldRendererRegistry, ActionHandlerRegistry } from '@manifesto-ai/ui'
import { getDefaultSemanticRegistry } from '@manifesto-ai/ui'
import { useFormRuntime } from '../../composables/useFormRuntime'
import SectionRenderer from './SectionRenderer.vue'
import type { FieldRendererComponent, FormActionHandlerContext } from '../../types'
import { getDefaultFieldRegistry } from '../../registry'
import { getDefaultActionRegistry } from '../../registry/actionRegistry'

const props = withDefaults(
  defineProps<{
    schema: FormViewSchema
    initialValues?: Record<string, unknown>
    context?: Partial<EvaluationContext>
    entitySchema?: EntitySchema
    readonly?: boolean
    includeHiddenFields?: boolean
    fieldRegistry?: FieldRendererRegistry<FieldRendererComponent>
    semanticRegistry?: SemanticRendererRegistry
    actionRegistry?: ActionHandlerRegistry<FormActionHandlerContext>
    liveValidators?: ReadonlyMap<string, readonly LightweightValidator[]>
    uiStateHints?: Readonly<Record<string, unknown>>
    fetchHandler?: FetchHandler
    navigateHandler?: NavigateHandler
    emitHandler?: EmitHandler
    debug?: boolean
  }>(),
  {
    readonly: false,
    includeHiddenFields: true,
    debug: false,
  }
)

const emit = defineEmits<{
  (e: 'submit', data: Record<string, unknown>): void
  (e: 'change', fieldId: string, value: unknown): void
  (e: 'validate', isValid: boolean): void
  (e: 'error', error: FormRuntimeError): void
  (e: 'runtime-ready', runtime: FormRuntime): void
  (e: 'action', actionId: string): void
}>()

const runtime = useFormRuntime(props.schema, {
  initialValues: props.initialValues,
  context: props.context,
  entitySchema: props.entitySchema,
  fetchHandler: props.fetchHandler,
  navigateHandler: props.navigateHandler,
  emitHandler: props.emitHandler,
  debug: props.debug,
})

const registry = computed(() => props.fieldRegistry ?? getDefaultFieldRegistry())
const semantic = computed(() => props.semanticRegistry ?? getDefaultSemanticRegistry())
const actions = computed(() => props.actionRegistry ?? getDefaultActionRegistry())

const semanticTree = ref<ResolvedFormSemanticNode<FieldRendererComponent> | null>(null)
const missingRenderers = ref<string[]>([])

const rebuildSemanticTree = async () => {
  const contract = { kind: 'form' as const, view: props.schema, state: runtime.getState() }
  const tree = semantic.value.build(contract, {
    includeHidden: props.includeHiddenFields,
    liveValidators: props.liveValidators,
    uiState: props.uiStateHints,
  })
  const { tree: resolved, missing } = await resolveFieldRenderers(tree, registry.value)
  semanticTree.value = resolved as ResolvedFormSemanticNode<FieldRendererComponent>
  missingRenderers.value = [...missing]
}

watch(
  () => [runtime.values.value, runtime.fields.value, runtime.isDirty.value, runtime.isValid.value, runtime.isSubmitting.value],
  () => {
    rebuildSemanticTree()
  },
  { deep: true }
)

onMounted(() => {
  rebuildSemanticTree()
  const rt = runtime.getRuntime()
  if (rt) {
    emit('runtime-ready', rt as FormRuntime)
  }
})

watch(
  () => runtime.error.value,
  (err) => {
    if (err) emit('error', err)
  }
)

watch(
  () => runtime.values.value,
  (values, prev) => {
    if (!prev) return
    for (const key of Object.keys(values)) {
      if (values[key] !== prev[key]) {
        emit('change', key, values[key])
      }
    }
  },
  { deep: true }
)

const handleSubmit = async () => {
  const data = await runtime.submit()
  emit('validate', runtime.isValid.value)
  if (!runtime.isValid.value || !data) return
  emit('submit', data)
}

const readonly = computed(() => props.readonly)

defineExpose({
  runtime,
  semanticTree,
})

const handleAction = (action: ActionSemanticNode) => {
  const handler = actions.value.get(action.actionId)
  const rt = runtime.getRuntime()
  if (handler && rt) {
    handler({ actionId: action.actionId, runtime: rt as FormRuntime, node: action })
  }
  emit('action', action.actionId)
}
</script>

// packages/react/src/components/form/FormRenderer.tsx
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type {
  EvaluationContext,
  FetchHandler,
  NavigateHandler,
  EmitHandler,
  FormRuntime,
  FormRuntimeError,
} from '@manifesto-ai/engine'
import type { EntitySchema, FormViewSchema } from '@manifesto-ai/schema'
import {
  resolveFieldRenderers,
  type ResolvedFieldSemanticNode,
  type ResolvedFormSemanticNode,
  type ResolvedSectionSemanticNode,
  type LightweightValidator,
  type SemanticBuildOptions,
} from '@manifesto-ai/ui'
import type { FieldRendererRegistry, SemanticRendererRegistry, ActionHandlerRegistry } from '@manifesto-ai/ui'
import { getDefaultSemanticRegistry } from '@manifesto-ai/ui'
import { useFormRuntime } from '../../hooks/useFormRuntime'
import SectionRenderer from './SectionRenderer'
import type { FieldRendererComponent } from '../../types'
import { getDefaultFieldRegistry, getDefaultActionRegistry } from '../../registry'
import type { FormActionHandler } from '../../types'
import { ActionButtons } from '../actions/ActionButtons'

export interface FormRendererProps {
  schema: FormViewSchema
  initialValues?: Record<string, unknown>
  context?: Partial<EvaluationContext>
  entitySchema?: EntitySchema
  readonly?: boolean
  includeHiddenFields?: boolean
  fieldRegistry?: FieldRendererRegistry<FieldRendererComponent>
  semanticRegistry?: SemanticRendererRegistry
  actionRegistry?: ActionHandlerRegistry<FormActionHandler>
  liveValidators?: ReadonlyMap<string, readonly LightweightValidator[]>
  uiStateHints?: Readonly<Record<string, unknown>>
  fetchHandler?: FetchHandler
  navigateHandler?: NavigateHandler
  emitHandler?: EmitHandler
  debug?: boolean
  onSubmit?: (data: Record<string, unknown>) => void
  onChange?: (fieldId: string, value: unknown) => void
  onValidate?: (isValid: boolean) => void
  onError?: (error: FormRuntimeError) => void
  onRuntimeReady?: (runtime: FormRuntime) => void
  renderField?: (
    field: ResolvedFieldSemanticNode<FieldRendererComponent>
  ) => React.ReactNode
  renderSection?: (
    section: ResolvedSectionSemanticNode<FieldRendererComponent>,
    children: React.ReactNode
  ) => React.ReactNode
  renderHeader?: (tree: ResolvedFormSemanticNode<FieldRendererComponent>) => React.ReactNode
  renderFooter?: (tree: ResolvedFormSemanticNode<FieldRendererComponent>) => React.ReactNode
}

export const FormRenderer: React.FC<FormRendererProps> = ({
  schema,
  initialValues,
  context,
  entitySchema,
  readonly = false,
  includeHiddenFields = true,
  fieldRegistry,
  semanticRegistry,
  actionRegistry,
  liveValidators,
  uiStateHints,
  fetchHandler,
  navigateHandler,
  emitHandler,
  debug = false,
  onSubmit,
  onChange,
  onValidate,
  onError,
  onRuntimeReady,
  renderField,
  renderSection,
  renderHeader,
  renderFooter,
}) => {
  const runtime = useFormRuntime(schema, {
    initialValues,
    context,
    entitySchema,
    fetchHandler,
    navigateHandler,
    emitHandler,
    debug,
  })

  const registry = useMemo(
    () => fieldRegistry ?? getDefaultFieldRegistry(),
    [fieldRegistry]
  )
  const semantic = useMemo(
    () => semanticRegistry ?? getDefaultSemanticRegistry(),
    [semanticRegistry]
  )
  const actions = useMemo(
    () => actionRegistry ?? getDefaultActionRegistry(),
    [actionRegistry]
  )

  const [semanticTree, setSemanticTree] = useState<ResolvedFormSemanticNode<FieldRendererComponent> | null>(null)
  const [missingRenderers, setMissingRenderers] = useState<readonly string[]>([])

  // Build semantic tree whenever runtime state changes
  useEffect(() => {
    if (!runtime.isInitialized) return

    const contract = { kind: 'form' as const, view: schema, state: runtime.getState() }
    const options: SemanticBuildOptions = {
      includeHidden: includeHiddenFields,
      liveValidators,
      uiState: uiStateHints,
    }
    const tree = semantic.build(contract, options)

    resolveFieldRenderers(tree, registry).then(({ tree: resolved, missing }) => {
      setSemanticTree(resolved as ResolvedFormSemanticNode<FieldRendererComponent>)
      setMissingRenderers(missing)
    })
  }, [
    schema,
    runtime.values,
    runtime.fields,
    runtime.isDirty,
    runtime.isValid,
    runtime.isSubmitting,
    runtime.isInitialized,
    includeHiddenFields,
    semantic,
    registry,
  ])

  // Submit handler
  const handleSubmit = useCallback(
    async (e?: React.FormEvent) => {
      e?.preventDefault()
      const data = await runtime.submit()
      onValidate?.(runtime.isValid)
      if (!runtime.isValid || !data) return
      onSubmit?.(data)
    },
    [runtime, onSubmit, onValidate]
  )

  // Value change detection (propagate to onChange)
  const prevValues = useRef<Record<string, unknown>>(runtime.values)
  useEffect(() => {
    if (!onChange) return
    const current = runtime.values
    const prev = prevValues.current
    for (const key of Object.keys(current)) {
      if (current[key] !== prev[key]) {
        onChange(key, current[key])
      }
    }
    prevValues.current = { ...current }
  }, [runtime.values, onChange])

  // Error callback
  useEffect(() => {
    if (runtime.error) {
      onError?.(runtime.error)
    }
  }, [runtime.error, onError])

  // Runtime ready callback
  const runtimeReadyCalledRef = useRef(false)
  useEffect(() => {
    if (runtime.isInitialized && onRuntimeReady && !runtimeReadyCalledRef.current) {
      const internalRuntime = runtime.getRuntime()
      if (internalRuntime) {
        runtimeReadyCalledRef.current = true
        onRuntimeReady(internalRuntime)
      }
    }
  }, [runtime.isInitialized, onRuntimeReady, runtime])

  const content = useMemo(() => {
    if (!semanticTree) return null

    // const handleAction = (action: ActionSemanticNode) => {
    //   const handler = actions.get(action.actionId)
    //   if (handler) {
    //     handler({ actionId: action.actionId, runtime: runtime.getRuntime()!, node: action })
    //   }
    // }

    const sections = semanticTree.sections.map((section) => {
      const sectionContent = (
        <SectionRenderer
          key={section.id}
          section={section}
          readonly={readonly}
          onChange={(fieldId, value) => runtime.setFieldValue(fieldId, value)}
          renderField={renderField}
          liveValidators={liveValidators}
        />
      )
      return renderSection ? renderSection(section, sectionContent) : sectionContent
    })

    return (
      <>
        {renderHeader ? (
          renderHeader(semanticTree)
        ) : (
          semanticTree.headerActions && semanticTree.headerActions.length > 0 && runtime.getRuntime() && (
            <ActionButtons actions={semanticTree.headerActions} registry={actions} runtime={runtime.getRuntime()} />
          )
        )}
        {sections}
        {renderFooter ? (
          renderFooter(semanticTree)
        ) : (
          <footer className="mfs-form__footer">
            <button type="submit" className="mfs-button mfs-button--primary" disabled={!runtime.isValid || runtime.isSubmitting}>
              Submit
            </button>
            {semanticTree.footerActions && semanticTree.footerActions.length > 0 && runtime.getRuntime() && (
              <ActionButtons actions={semanticTree.footerActions} registry={actions} runtime={runtime.getRuntime()} />
            )}
          </footer>
        )}
        {missingRenderers.length > 0 && (
          <div className="mfs-warning">
            Missing renderers for: {missingRenderers.join(', ')}
          </div>
        )}
      </>
    )
  }, [semanticTree, renderHeader, renderFooter, renderSection, renderField, runtime, readonly, missingRenderers])

  return (
    <form className="mfs-form" onSubmit={handleSubmit}>
      {!runtime.isInitialized && <div className="mfs-form__loading">Loading...</div>}
      {runtime.error && <div className="mfs-form__error">{'message' in runtime.error ? runtime.error.message : runtime.error.type}</div>}
      {runtime.isInitialized && !runtime.error && content}
    </form>
  )
}

export default FormRenderer
