// packages/vue/src/components/form/SectionRenderer.vue
<template>
  <!-- Skip rendering if section is hidden -->
  <section
    v-if="!section.hidden"
    class="mvs-section"
    :data-section-id="section.id"
    v-bind="highlightAttrs"
  >
    <header v-if="section.title || section.description" class="mvs-section__header">
      <h3 v-if="section.title" class="mvs-section__title">{{ section.title }}</h3>
      <p v-if="section.description" class="mvs-section__description">{{ section.description }}</p>
    </header>
    <div class="mvs-section__fields">
      <template v-for="field in section.fields" :key="field.id">
        <slot name="field" :field="field">
          <FieldRenderer
            :node="field"
            :readonly="readonly"
            :live-validators="liveValidators"
            @change="(v) => onChange(field.fieldId, v)"
          />
        </slot>
      </template>
    </div>
  </section>
</template>

<script setup lang="ts">
import FieldRenderer from './FieldRenderer.vue'
import type { ResolvedSectionSemanticNode } from '@manifesto-ai/ui'
import type { FieldRendererComponent } from '../../types'
import { useHighlight } from '../../composables/useHighlight'

const props = defineProps<{
  section: ResolvedSectionSemanticNode<FieldRendererComponent>
  readonly?: boolean
  onChange: (fieldId: string, value: unknown) => void
  liveValidators?: ReadonlyMap<string, readonly import('@manifesto-ai/ui').LightweightValidator[]>
}>()

// Highlight support for sections
const { dataAttributes: highlightAttrs } = useHighlight(`section:${props.section.id}`)
</script>

// packages/react/src/components/form/SectionRenderer.tsx
import React from 'react'
import type { ResolvedSectionSemanticNode } from '@manifesto-ai/ui'
import type { FieldRendererComponent } from '../../types'
import FieldRenderer from './FieldRenderer'
import { useHighlight } from '../../hooks/useHighlight'

interface SectionRendererProps {
  section: ResolvedSectionSemanticNode<FieldRendererComponent>
  readonly?: boolean
  onChange: (fieldId: string, value: unknown) => void
  renderField?: (field: ResolvedSectionSemanticNode<FieldRendererComponent>['fields'][number]) => React.ReactNode
  liveValidators?: ReadonlyMap<string, readonly import('@manifesto-ai/ui').LightweightValidator[]>
}

const SectionRenderer: React.FC<SectionRendererProps> = ({
  section,
  readonly,
  onChange,
  renderField,
  liveValidators,
}) => {
  // Highlight support for sections
  const { dataAttributes } = useHighlight(`section:${section.id}`)

  // Skip rendering if section is hidden
  if (section.hidden) return null
  if (!section.fields.length) return null

  return (
    <section className="mfs-section" data-section-id={section.id} {...dataAttributes}>
      {(section.title || section.description) && (
        <header className="mfs-section__header">
          {section.title && <h3 className="mfs-section__title">{section.title}</h3>}
          {section.description && <p className="mfs-section__description">{section.description}</p>}
        </header>
      )}

      <div className="mfs-section__fields">
        {section.fields.map((field) =>
          renderField ? (
            <React.Fragment key={field.id}>{renderField(field)}</React.Fragment>
          ) : (
            <FieldRenderer
              key={field.id}
              node={field}
              readonly={readonly}
              onChange={onChange}
              liveValidators={liveValidators}
            />
          )
        )}
      </div>
    </section>
  )
}

export default SectionRenderer
