// packages/vue/src-legacy/components/form/FormRenderer.vue
<script setup lang="ts">
/**
 * FormRenderer - 폼 렌더러 최상위 컴포넌트
 *
 * ViewSchema를 받아 자동으로 폼 UI를 렌더링
 * useFormRuntime과 통합하여 상태 관리
 * ComponentRegistry를 통한 커스텀 컴포넌트 지원
 */
import { provide, computed, toRef, shallowRef, watch } from 'vue'
import type { FormViewSchema, EntitySchema } from '@manifesto-ai/schema'
import type { EvaluationContext, FormRuntimeError, FetchHandler, NavigateHandler, EmitHandler } from '@manifesto-ai/engine'
import { useFormRuntime } from '../../composables/useFormRuntime'
import { getDefaultRegistry } from '../registry/ComponentRegistry'
import type { IComponentRegistry } from '../../types/component'
import {
  FORM_RUNTIME_KEY,
  COMPONENT_REGISTRY_KEY,
  FORM_READONLY_KEY,
} from '../../types/component'
import SectionRenderer from './SectionRenderer.vue'
import DebugPanel from './DebugPanel.vue'

interface Props {
  /** View 스키마 */
  schema: FormViewSchema
  /** 초기값 */
  initialValues?: Record<string, unknown>
  /** 평가 컨텍스트 */
  context?: Partial<EvaluationContext>
  /** Entity 스키마 (검증용) */
  entitySchema?: EntitySchema
  /** 읽기 전용 모드 */
  readonly?: boolean
  /** 커스텀 컴포넌트 레지스트리 */
  componentRegistry?: IComponentRegistry
  /** Fetch 핸들러 (API 호출용) */
  fetchHandler?: FetchHandler
  /** Navigate 핸들러 (라우팅용) */
  navigateHandler?: NavigateHandler
  /** Emit 핸들러 (이벤트 발행용) */
  emitHandler?: EmitHandler
  /** 디버그 모드 */
  debug?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  initialValues: () => ({}),
  readonly: false,
  debug: false,
})

const emit = defineEmits<{
  (e: 'submit', data: Record<string, unknown>): void
  (e: 'change', fieldId: string, value: unknown): void
  (e: 'validate', isValid: boolean): void
  (e: 'error', error: FormRuntimeError): void
}>()

// 스키마를 shallowRef로 감싸서 useFormRuntime에 전달
const schemaRef = shallowRef<FormViewSchema>(props.schema)

// Props 변경 감지
watch(() => props.schema, (newSchema) => {
  schemaRef.value = newSchema
})

// 런타임 초기화
const runtime = useFormRuntime(schemaRef, {
  initialValues: props.initialValues,
  context: props.context,
  entitySchema: props.entitySchema,
  fetchHandler: props.fetchHandler,
  navigateHandler: props.navigateHandler,
  emitHandler: props.emitHandler,
  debug: props.debug,
})

// 레지스트리 결정 (prop 우선, 없으면 기본)
const registry = computed(() => props.componentRegistry ?? getDefaultRegistry())

// Provide to child components
provide(FORM_RUNTIME_KEY, runtime)
provide(COMPONENT_REGISTRY_KEY, registry)
provide(FORM_READONLY_KEY, toRef(() => props.readonly))

// 섹션 목록 (visible 필터링은 SectionRenderer에서 처리)
const sections = computed(() => props.schema.sections ?? [])

// Submit 핸들러
const handleSubmit = async () => {
  runtime.validateAll()

  emit('validate', runtime.isValid.value)

  if (!runtime.isValid.value) {
    return
  }

  const data = await runtime.submit()
  if (data) {
    emit('submit', data)
  }
}

// Reset 핸들러
const handleReset = () => {
  runtime.reset()
}

// 에러 감지 및 emit
watch(
  () => runtime.error.value,
  (error) => {
    if (error) {
      emit('error', error)
    }
  }
)

// 값 변경 감지 및 emit
watch(
  () => runtime.values,
  (values, oldValues) => {
    if (!oldValues) return
    for (const key of Object.keys(values)) {
      if (values[key] !== oldValues[key]) {
        emit('change', key, values[key])
      }
    }
  },
  { deep: true }
)

// Expose to parent component
defineExpose({
  /** 런타임 인스턴스 */
  runtime,
  /** 폼 제출 */
  submit: handleSubmit,
  /** 폼 리셋 */
  reset: handleReset,
  /** 전체 검증 */
  validate: runtime.validateAll,
  /** 폼 값들 */
  values: runtime.values,
  /** 유효성 상태 */
  isValid: runtime.isValid,
  /** 변경 상태 */
  isDirty: runtime.isDirty,
})
</script>

<template>
  <form
    class="form-renderer"
    :class="{
      'form-renderer--readonly': readonly,
      'form-renderer--loading': !runtime.isInitialized.value,
      'form-renderer--error': runtime.error.value,
    }"
    @submit.prevent="handleSubmit"
  >
    <!-- Header Slot -->
    <header v-if="$slots.header" class="form-renderer__header">
      <slot name="header" />
    </header>

    <!-- Loading State -->
    <div v-if="!runtime.isInitialized.value" class="form-renderer__loading">
      <slot name="loading">
        <span>Loading...</span>
      </slot>
    </div>

    <!-- Error State -->
    <div v-else-if="runtime.error.value" class="form-renderer__error">
      <slot name="error" :error="runtime.error.value">
        <span class="form-renderer__error-message">
          {{ 'message' in runtime.error.value ? runtime.error.value.message : runtime.error.value.type }}
        </span>
      </slot>
    </div>

    <!-- Form Content -->
    <div v-else class="form-renderer__content">
      <SectionRenderer
        v-for="section in sections"
        :key="section.id"
        :section="section"
      >
        <!-- Section Header Slot 전달 -->
        <template #header>
          <slot :name="`section-${section.id}-header`" :section="section" />
        </template>

        <!-- Section Footer Slot 전달 -->
        <template #footer>
          <slot :name="`section-${section.id}-footer`" :section="section" />
        </template>

        <!-- Field Slots 전달 -->
        <template
          v-for="field in section.fields"
          :key="`slot-${field.id}`"
          #[`field-${field.id}`]
        >
          <slot
            :name="`field-${field.id}`"
            :field="field"
            :meta="runtime.getField(field.id)"
            :value="runtime.values[field.id]"
            :set-value="(v: unknown) => runtime.setFieldValue(field.id, v)"
            :errors="runtime.getFieldErrors(field.id)"
            :disabled="runtime.isFieldDisabled(field.id)"
            :hidden="runtime.isFieldHidden(field.id)"
          >
            <!-- 기본 렌더링은 SectionRenderer에서 처리 -->
          </slot>
        </template>
      </SectionRenderer>
    </div>

    <!-- Footer Slot -->
    <footer v-if="$slots.footer" class="form-renderer__footer">
      <slot
        name="footer"
        :submit="handleSubmit"
        :reset="handleReset"
        :is-valid="runtime.isValid.value"
        :is-dirty="runtime.isDirty.value"
        :is-submitting="runtime.isSubmitting.value"
      />
    </footer>

    <!-- Debug Panel -->
    <DebugPanel
      v-if="debug && runtime.isInitialized.value"
      :runtime="runtime"
      :schema="schema"
    />
  </form>
</template>

<style>
.form-renderer {
  /* 기본 스타일 */
}

.form-renderer__header {
  margin-bottom: 1.5rem;
}

.form-renderer__loading {
  padding: 2rem;
  text-align: center;
  color: #6b7280;
}

.form-renderer__error {
  padding: 1rem;
  background-color: #fef2f2;
  border: 1px solid #fecaca;
  border-radius: 0.375rem;
  color: #dc2626;
}

.form-renderer__error-message {
  font-size: 0.875rem;
}

.form-renderer__content {
  /* Sections container */
}

.form-renderer__footer {
  margin-top: 1.5rem;
  padding-top: 1rem;
  border-top: 1px solid #e5e7eb;
}
</style>

// packages/react/src-legacy/components/form/FormRenderer.tsx
/**
 * FormRenderer - Top-level form renderer component
 *
 * Receives ViewSchema and automatically renders form UI
 * Integrates with useFormRuntime for state management
 * Supports custom components via ComponentRegistry
 */

import React, { useMemo, useCallback, useEffect, useRef } from 'react'
import type { FormViewSchema, ViewField, EntitySchema } from '@manifesto-ai/schema'
import type { EvaluationContext, FormRuntimeError, FetchHandler, NavigateHandler, EmitHandler, FieldMeta, FormRuntime } from '@manifesto-ai/engine'
import { useFormRuntime as useFormRuntimeHook } from '../../hooks/useFormRuntime'
import { getDefaultRegistry } from '../registry/ComponentRegistry'
import { FormContext } from '../FormContext'
import type { IComponentRegistry } from '../../types/component'
import SectionRenderer from './SectionRenderer'
import DebugPanel from './DebugPanel'

/**
 * Footer render props
 */
export interface FormFooterProps {
  submit: () => void
  reset: () => void
  isValid: boolean
  isDirty: boolean
  isSubmitting: boolean
}

/**
 * Field render props
 */
export interface FieldRenderProps {
  field: ViewField
  meta: FieldMeta | undefined
  value: unknown
  setValue: (value: unknown) => void
  errors: readonly string[]
  disabled: boolean
  hidden: boolean
}

export interface FormRendererProps {
  /** View schema */
  schema: FormViewSchema
  /** Initial values */
  initialValues?: Record<string, unknown>
  /** Evaluation context */
  context?: Partial<EvaluationContext>
  /** Entity schema (for validation) */
  entitySchema?: EntitySchema
  /** Readonly mode */
  readonly?: boolean
  /** Custom component registry */
  componentRegistry?: IComponentRegistry
  /** Fetch handler (for API calls) */
  fetchHandler?: FetchHandler
  /** Navigate handler (for routing) */
  navigateHandler?: NavigateHandler
  /** Emit handler (for events) */
  emitHandler?: EmitHandler
  /** Debug mode */
  debug?: boolean
  /** Submit handler */
  onSubmit?: (data: Record<string, unknown>) => void
  /** Change handler */
  onChange?: (fieldId: string, value: unknown) => void
  /** Validate handler */
  onValidate?: (isValid: boolean) => void
  /** Error handler */
  onError?: (error: FormRuntimeError) => void
  /** Runtime ready callback (for AI integration) */
  onRuntimeReady?: (runtime: FormRuntime) => void
  /** Header render prop */
  renderHeader?: () => React.ReactNode
  /** Loading render prop */
  renderLoading?: () => React.ReactNode
  /** Error render prop */
  renderError?: (error: FormRuntimeError) => React.ReactNode
  /** Footer render prop */
  renderFooter?: (props: FormFooterProps) => React.ReactNode
  /** Section header render prop */
  renderSectionHeader?: (sectionId: string) => React.ReactNode
  /** Section footer render prop */
  renderSectionFooter?: (sectionId: string) => React.ReactNode
  /** Field render prop (override specific field) */
  renderField?: (fieldId: string, props: FieldRenderProps) => React.ReactNode | null
}

export const FormRenderer: React.FC<FormRendererProps> = ({
  schema,
  initialValues = {},
  context,
  entitySchema,
  readonly = false,
  componentRegistry,
  fetchHandler,
  navigateHandler,
  emitHandler,
  debug = false,
  onSubmit,
  onChange,
  onValidate,
  onError,
  onRuntimeReady,
  renderHeader,
  renderLoading,
  renderError,
  renderFooter,
  renderSectionHeader,
  renderSectionFooter,
  renderField,
}) => {
  // Initialize runtime
  const runtime = useFormRuntimeHook(schema, {
    initialValues,
    context,
    entitySchema,
    fetchHandler,
    navigateHandler,
    emitHandler,
    debug,
  })

  // Determine registry (prop priority, then default)
  const registry = useMemo(
    () => componentRegistry ?? getDefaultRegistry(),
    [componentRegistry]
  )

  // Section list
  const sections = useMemo(() => schema.sections ?? [], [schema.sections])

  // Submit handler
  const handleSubmit = useCallback(
    async (e?: React.FormEvent) => {
      e?.preventDefault()

      runtime.validateAll()
      onValidate?.(runtime.isValid)

      if (!runtime.isValid) {
        return
      }

      const data = await runtime.submit()
      if (data) {
        onSubmit?.(data)
      }
    },
    [runtime, onSubmit, onValidate]
  )

  // Reset handler
  const handleReset = useCallback(() => {
    runtime.reset()
  }, [runtime])

  // Error detection and callback
  useEffect(() => {
    if (runtime.error) {
      onError?.(runtime.error)
    }
  }, [runtime.error, onError])

  // Runtime ready callback (for AI integration)
  // Use ref to avoid re-running effect when runtime object changes
  const runtimeRef = useRef(runtime)
  runtimeRef.current = runtime
  const runtimeReadyCalledRef = useRef(false)

  useEffect(() => {
    // Only call once when initialized
    if (runtime.isInitialized && onRuntimeReady && !runtimeReadyCalledRef.current) {
      const internalRuntime = runtimeRef.current.getRuntime()
      if (internalRuntime) {
        runtimeReadyCalledRef.current = true
        onRuntimeReady(internalRuntime)
      }
    }
  }, [runtime.isInitialized, onRuntimeReady])

  // Value change detection and callback
  const prevValues = React.useRef<Record<string, unknown>>(runtime.values)
  useEffect(() => {
    if (!onChange) return

    const currentValues = runtime.values
    const prev = prevValues.current

    for (const key of Object.keys(currentValues)) {
      if (currentValues[key] !== prev[key]) {
        onChange(key, currentValues[key])
      }
    }

    prevValues.current = { ...currentValues }
  }, [runtime.values, onChange])

  // Context value
  const contextValue = useMemo(
    () => ({
      runtime,
      registry,
      readonly,
    }),
    [runtime, registry, readonly]
  )

  // Form class names
  const formClassName = useMemo(() => {
    const classes = ['form-renderer']
    if (readonly) classes.push('form-renderer--readonly')
    if (!runtime.isInitialized) classes.push('form-renderer--loading')
    if (runtime.error) classes.push('form-renderer--error')
    return classes.join(' ')
  }, [readonly, runtime.isInitialized, runtime.error])

  return (
    <FormContext.Provider value={contextValue}>
      <form className={formClassName} onSubmit={handleSubmit}>
        {/* Header */}
        {renderHeader && <header className="form-renderer__header">{renderHeader()}</header>}

        {/* Loading State */}
        {!runtime.isInitialized && (
          <div className="form-renderer__loading">
            {renderLoading ? renderLoading() : <span>Loading...</span>}
          </div>
        )}

        {/* Error State */}
        {runtime.isInitialized && runtime.error && (
          <div className="form-renderer__error">
            {renderError ? (
              renderError(runtime.error)
            ) : (
              <span className="form-renderer__error-message">
                {'message' in runtime.error ? runtime.error.message : runtime.error.type}
              </span>
            )}
          </div>
        )}

        {/* Form Content */}
        {runtime.isInitialized && !runtime.error && (
          <div className="form-renderer__content">
            {sections.map((section) => (
              <SectionRenderer
                key={section.id}
                section={section}
                renderHeader={
                  renderSectionHeader ? () => renderSectionHeader(section.id) : undefined
                }
                renderFooter={
                  renderSectionFooter ? () => renderSectionFooter(section.id) : undefined
                }
                renderField={
                  renderField
                    ? (fieldId) => {
                        const field = section.fields.find((f) => f.id === fieldId)
                        if (!field) return null
                        return renderField(fieldId, {
                          field,
                          meta: runtime.getField(fieldId),
                          value: runtime.values[fieldId],
                          setValue: (v) => runtime.setFieldValue(fieldId, v),
                          errors: runtime.getFieldErrors(fieldId),
                          disabled: runtime.isFieldDisabled(fieldId),
                          hidden: runtime.isFieldHidden(fieldId),
                        })
                      }
                    : undefined
                }
              />
            ))}
          </div>
        )}

        {/* Footer */}
        {renderFooter && (
          <footer className="form-renderer__footer">
            {renderFooter({
              submit: handleSubmit,
              reset: handleReset,
              isValid: runtime.isValid,
              isDirty: runtime.isDirty,
              isSubmitting: runtime.isSubmitting,
            })}
          </footer>
        )}

        {/* Debug Panel */}
        {debug && runtime.isInitialized && <DebugPanel runtime={runtime} schema={schema} />}
      </form>
    </FormContext.Provider>
  )
}

export default FormRenderer
