// packages/react/src-legacy/components/inputs/CheckboxInput.tsx
/**
 * CheckboxInput - Checkbox input component
 */

import React from 'react'
import type { InputComponentProps } from '../../types/component'

export const CheckboxInput: React.FC<InputComponentProps> = ({
  fieldId,
  value,
  onChange,
  disabled = false,
  readonly = false,
  componentProps = {},
  hasError = false,
  onFocus,
  onBlur,
}) => {
  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (!readonly) {
      onChange(e.target.checked)
    }
  }

  const { label, ...restProps } = componentProps as { label?: string }

  return (
    <label
      className={`input-checkbox ${hasError ? 'input-checkbox--error' : ''} ${disabled ? 'input-checkbox--disabled' : ''}`}
    >
      <input
        type="checkbox"
        id={fieldId}
        checked={Boolean(value)}
        disabled={disabled}
        className="input-checkbox__input"
        onChange={handleChange}
        onFocus={onFocus}
        onBlur={onBlur}
        {...restProps}
      />
      {label && <span className="input-checkbox__label">{label}</span>}
    </label>
  )
}

export default CheckboxInput

// apps/vue-example/src/components/manifesto-vuetify/CheckboxInput.vue
<script setup lang="ts">
/**
 * CheckboxInput - Vuetify v-checkbox wrapper
 */
import type { FieldComponentProps } from '@manifesto-ai/vue'
import { computed } from 'vue'

const props = defineProps<FieldComponentProps>()

const hasError = computed(() => props.errors.length > 0)
const fieldProps = computed(() => props.field.state.props ?? {})
const label = computed(() => (fieldProps.value.label as string) || props.field.label)
const handleChange = (value: unknown) => props.onChange(value ?? false)
</script>

<template>
  <v-checkbox
    :id="props.field.fieldId"
    :model-value="props.value"
    @update:model-value="handleChange"
    :disabled="props.disabled"
    :readonly="props.readonly"
    :error="hasError"
    :label="label"
  />
</template>
