// packages/react/src-legacy/components/inputs/MultiSelectInput.tsx
/**
 * MultiSelectInput - Multiple select component
 */

import React from 'react'
import type { InputComponentProps } from '../../types/component'

export const MultiSelectInput: React.FC<InputComponentProps> = ({
  fieldId,
  value,
  onChange,
  disabled = false,
  readonly = false,
  placeholder,
  componentProps = {},
  hasError = false,
  options = [],
  onFocus,
  onBlur,
}) => {
  const selectedValues = Array.isArray(value) ? value : []

  const handleChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const selectedOptions = Array.from(e.target.selectedOptions, (option) => option.value)
    onChange(selectedOptions)
  }

  return (
    <select
      id={fieldId}
      multiple
      value={selectedValues}
      disabled={disabled || readonly}
      className={`input-multi-select ${hasError ? 'input-multi-select--error' : ''} ${disabled ? 'input-multi-select--disabled' : ''}`}
      onChange={handleChange}
      onFocus={onFocus}
      onBlur={onBlur}
      {...componentProps}
    >
      {placeholder && (
        <option value="" disabled>
          {placeholder}
        </option>
      )}
      {options.map((option) => (
        <option key={option.value} value={option.value} disabled={option.disabled}>
          {option.label}
        </option>
      ))}
    </select>
  )
}

export default MultiSelectInput

// apps/vue-example/src/components/manifesto-vuetify/MultiSelectInput.vue
<script setup lang="ts">
/**
 * MultiSelectInput - Vuetify v-select multiple wrapper
 */
import type { FieldComponentProps } from '@manifesto-ai/vue'
import { computed } from 'vue'

const props = defineProps<FieldComponentProps>()

const options = computed(() => props.field.state.options ?? [])
const hasError = computed(() => props.errors.length > 0)
const handleChange = (value: unknown) => props.onChange(value)
</script>

<template>
  <v-select
    :id="props.field.fieldId"
    :model-value="props.value"
    @update:model-value="handleChange"
    :items="options"
    item-title="label"
    item-value="value"
    :disabled="props.disabled"
    :readonly="props.readonly"
    :placeholder="props.field.placeholder"
    :error="hasError"
    multiple
    chips
    closable-chips
  />
</template>
