// packages/react/src-legacy/components/inputs/NumberInput.tsx
/**
 * NumberInput - Number input component
 */

import React from 'react'
import type { InputComponentProps } from '../../types/component'

export const NumberInput: React.FC<InputComponentProps> = ({
  fieldId,
  value,
  onChange,
  disabled = false,
  readonly = false,
  placeholder,
  componentProps = {},
  hasError = false,
  onFocus,
  onBlur,
}) => {
  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value
    onChange(val === '' ? null : Number(val))
  }

  // Convert value to string for input
  const inputValue = value != null ? String(value) : ''

  return (
    <input
      type="number"
      id={fieldId}
      value={inputValue}
      disabled={disabled}
      readOnly={readonly}
      placeholder={placeholder}
      className={`input-number ${hasError ? 'input-number--error' : ''} ${disabled ? 'input-number--disabled' : ''}`}
      onChange={handleChange}
      onFocus={onFocus}
      onBlur={onBlur}
      {...componentProps}
    />
  )
}

export default NumberInput

// apps/vue-example/src/components/manifesto-vuetify/NumberInput.vue
<script setup lang="ts">
/**
 * NumberInput - Vuetify v-text-field type=number wrapper
 */
import type { FieldComponentProps } from '@manifesto-ai/vue'
import { computed } from 'vue'

const props = defineProps<FieldComponentProps>()

const hasError = computed(() => props.errors.length > 0)
const handleUpdate = (value: string | number | null) => {
  if (value === '' || value === null) {
    props.onChange(null)
  } else {
    props.onChange(Number(value))
  }
}
</script>

<template>
  <v-text-field
    :id="props.field.fieldId"
    type="number"
    :model-value="props.value"
    @update:model-value="handleUpdate"
    :disabled="props.disabled"
    :readonly="props.readonly"
    :placeholder="props.field.placeholder"
    :error="hasError"
  />
</template>
