// apps/react-example/src/components/manifesto-shadcn/SliderInput.tsx
import type { FieldComponentProps } from '@manifesto-ai/react'
import { Slider } from '@/components/ui/slider'

export default function SliderInput({
  field,
  value,
  onChange,
  disabled,
}: FieldComponentProps) {
  const props = field.state.props ?? {}
  const min = (props.min as number) ?? 0
  const max = (props.max as number) ?? 100
  const step = (props.step as number) ?? 1

  return (
    <div className="flex items-center gap-4">
      <Slider
        id={field.fieldId}
        value={[value != null ? (value as number) : min]}
        onValueChange={([val]) => onChange(val)}
        disabled={disabled}
        min={min}
        max={max}
        step={step}
        className="flex-1"
      />
      <span className="w-12 text-right text-sm text-muted-foreground">
        {value != null ? String(value) : String(min)}
      </span>
    </div>
  )
}

// apps/vue-example/src/components/manifesto-vuetify/SliderInput.vue
<script setup lang="ts">
/**
 * SliderInput - Vuetify v-slider wrapper
 */
import type { FieldComponentProps } from '@manifesto-ai/vue'
import { computed } from 'vue'

const props = defineProps<FieldComponentProps>()

const hasError = computed(() => props.errors.length > 0)
const fieldProps = computed(() => props.field.state.props ?? {})
const min = computed(() => (fieldProps.value.min as number) ?? 0)
const max = computed(() => (fieldProps.value.max as number) ?? 100)
const step = computed(() => (fieldProps.value.step as number) ?? 1)
const showValue = computed(() => (fieldProps.value.showValue as boolean) ?? true)
const handleChange = (value: unknown) => props.onChange(value)
</script>

<template>
  <v-slider
    :id="props.field.fieldId"
    :model-value="props.value as number"
    @update:model-value="handleChange"
    :disabled="props.disabled"
    :readonly="props.readonly"
    :error="hasError"
    :min="min"
    :max="max"
    :step="step"
    :thumb-label="showValue ? 'always' : false"
    color="primary"
  />
</template>
