// apps/react-example/src/components/manifesto-shadcn/ToggleInput.tsx
import type { FieldComponentProps } from '@manifesto-ai/react'
import { Switch } from '@/components/ui/switch'
import { Label } from '@/components/ui/label'

export default function ToggleInput({
  field,
  value,
  onChange,
  disabled,
}: FieldComponentProps) {
  const props = field.state.props ?? {}
  const label = (props.label as string) || field.label

  return (
    <div className="flex items-center gap-2">
      <Switch
        id={field.fieldId}
        checked={value as boolean}
        onCheckedChange={onChange}
        disabled={disabled}
      />
      {label && (
        <Label htmlFor={field.fieldId} className="cursor-pointer">
          {label}
        </Label>
      )}
    </div>
  )
}

// apps/vue-example/src/components/manifesto-vuetify/ToggleInput.vue
<script setup lang="ts">
/**
 * ToggleInput - Vuetify v-switch wrapper
 */
import type { FieldComponentProps } from '@manifesto-ai/vue'
import { computed } from 'vue'

const props = defineProps<FieldComponentProps>()

const hasError = computed(() => props.errors.length > 0)
const fieldProps = computed(() => props.field.state.props ?? {})
const label = computed(() => (fieldProps.value.label as string) || props.field.label)
const handleChange = (value: unknown) => props.onChange(value ?? false)
</script>

<template>
  <v-switch
    :id="props.field.fieldId"
    :model-value="props.value"
    @update:model-value="handleChange"
    :disabled="props.disabled"
    :readonly="props.readonly"
    :error="hasError"
    :label="label"
    color="primary"
  />
</template>
