// packages/vue/src/components/fields/CheckboxField.vue
<template>
  <FieldWrapper v-bind="props">
    <label class="mvs-checkbox">
      <input
        type="checkbox"
        :checked="Boolean(props.value)"
        :disabled="props.disabled || props.readonly"
        @change="onToggle"
      />
      <span>{{ props.field.label }}</span>
    </label>
  </FieldWrapper>
</template>

<script setup lang="ts">
import FieldWrapper from './FieldWrapper.vue'
import type { FieldComponentProps } from '../../types'

const props = defineProps<FieldComponentProps>()

const onToggle = (event: Event) => {
  const target = event.target as HTMLInputElement
  props.onChange(target.checked)
}
</script>

// packages/react/src/components/fields/CheckboxField.tsx
import React from 'react'
import type { FieldComponentProps } from '../../types'
import { FieldWrapper } from './FieldWrapper'

const CheckboxField: React.FC<FieldComponentProps> = ({
  field,
  value,
  onChange,
  disabled,
  readonly,
  errors,
}) => {
  const checked = Boolean(value)

  return (
    <FieldWrapper field={field} value={value} onChange={onChange} disabled={disabled} readonly={readonly} errors={errors}>
      <label className="mfs-checkbox">
        <input
          type="checkbox"
          checked={checked}
          onChange={(e) => onChange(e.target.checked)}
          disabled={disabled || readonly}
        />
        <span>{field.label}</span>
      </label>
    </FieldWrapper>
  )
}

export default CheckboxField
