// packages/vue/src/components/fields/MultiSelectField.vue
<template>
  <FieldWrapper v-bind="props">
    <select
      class="mvs-select"
      multiple
      :value="selected"
      :disabled="props.disabled"
      :aria-readonly="props.readonly"
      @change="onChange"
    >
      <option
        v-for="opt in options"
        :key="opt.value"
        :value="opt.value"
        :disabled="opt.disabled"
      >
        {{ opt.label }}
      </option>
    </select>
  </FieldWrapper>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import FieldWrapper from './FieldWrapper.vue'
import type { FieldComponentProps } from '../../types'

const props = defineProps<FieldComponentProps>()

const options = computed(() => props.field.state.options ?? [])
const selected = computed(() => (Array.isArray(props.value) ? props.value.map(String) : []))

const onChange = (event: Event) => {
  const target = event.target as HTMLSelectElement
  const values = Array.from(target.selectedOptions).map((opt) => opt.value)
  props.onChange(values)
}
</script>

// packages/react/src/components/fields/MultiSelectField.tsx
import React from 'react'
import type { FieldComponentProps } from '../../types'
import { FieldWrapper } from './FieldWrapper'

const MultiSelectField: React.FC<FieldComponentProps> = ({
  field,
  value,
  onChange,
  disabled,
  readonly,
  errors,
}) => {
  const options = field.state.options ?? []
  const selectedValues = Array.isArray(value) ? value.map(String) : []

  const handleChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const newValues = Array.from(e.target.selectedOptions).map((opt) => opt.value)
    onChange(newValues)
  }

  return (
    <FieldWrapper field={field} value={value} onChange={onChange} disabled={disabled} readonly={readonly} errors={errors}>
      <select
        className="mfs-select"
        multiple
        value={selectedValues}
        onChange={handleChange}
        disabled={disabled}
        aria-readonly={readonly}
      >
        {options.map((opt) => (
          <option key={opt.value} value={opt.value} disabled={opt.disabled}>
            {opt.label}
          </option>
        ))}
      </select>
    </FieldWrapper>
  )
}

export default MultiSelectField
