// packages/vue/src/components/fields/NumberField.vue
<template>
  <FieldWrapper v-bind="props">
    <input
      class="mvs-input"
      type="number"
      :placeholder="props.field.placeholder"
      :value="numberValue"
      :disabled="props.disabled"
      :readonly="props.readonly"
      @input="onInput"
    />
  </FieldWrapper>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import FieldWrapper from './FieldWrapper.vue'
import type { FieldComponentProps } from '../../types'

const props = defineProps<FieldComponentProps>()

const numberValue = computed(() => {
  const v = props.value
  if (v === undefined || v === null || v === '') return ''
  return typeof v === 'number' ? v : Number(v)
})

const onInput = (event: Event) => {
  const target = event.target as HTMLInputElement
  props.onChange(target.value === '' ? null : Number(target.value))
}
</script>

// packages/react/src/components/fields/NumberField.tsx
import React from 'react'
import type { FieldComponentProps } from '../../types'
import { FieldWrapper } from './FieldWrapper'

const NumberField: React.FC<FieldComponentProps> = ({
  field,
  value,
  onChange,
  disabled,
  readonly,
  errors,
}) => {
  return (
    <FieldWrapper field={field} value={value} onChange={onChange} disabled={disabled} readonly={readonly} errors={errors}>
      <input
        className="mfs-input"
        type="number"
        value={value === undefined || value === null ? '' : Number(value)}
        placeholder={field.placeholder}
        onChange={(e) => onChange(e.target.value === '' ? null : Number(e.target.value))}
        disabled={disabled}
        readOnly={readonly}
      />
    </FieldWrapper>
  )
}

export default NumberField
