// packages/vue/src/components/fields/TextareaField.vue
<template>
  <FieldWrapper v-bind="props">
    <textarea
      class="mvs-textarea"
      :placeholder="props.field.placeholder"
      :value="stringValue"
      :disabled="props.disabled"
      :readonly="props.readonly"
      @input="onInput"
    />
  </FieldWrapper>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import FieldWrapper from './FieldWrapper.vue'
import type { FieldComponentProps } from '../../types'

const props = defineProps<FieldComponentProps>()

const stringValue = computed(() => {
  const v = props.value
  return v === undefined || v === null ? '' : String(v)
})

const onInput = (event: Event) => {
  const target = event.target as HTMLTextAreaElement
  props.onChange(target.value)
}
</script>

// packages/react/src/components/fields/TextareaField.tsx
import React from 'react'
import type { FieldComponentProps } from '../../types'
import { FieldWrapper } from './FieldWrapper'

const TextareaField: React.FC<FieldComponentProps> = ({
  field,
  value,
  onChange,
  disabled,
  readonly,
  errors,
}) => {
  return (
    <FieldWrapper field={field} value={value} onChange={onChange} disabled={disabled} readonly={readonly} errors={errors}>
      <textarea
        className="mfs-textarea"
        value={value === undefined || value === null ? '' : String(value)}
        placeholder={field.placeholder}
        onChange={(e) => onChange(e.target.value)}
        disabled={disabled}
        readOnly={readonly}
      />
    </FieldWrapper>
  )
}

export default TextareaField
