// packages/vue/src/components/fields/ToggleField.vue
<template>
  <FieldWrapper v-bind="props">
    <label class="mvs-toggle">
      <input
        type="checkbox"
        :checked="Boolean(props.value)"
        :disabled="props.disabled || props.readonly"
        @change="onToggle"
      />
      <span class="mvs-toggle__track"><span class="mvs-toggle__thumb" /></span>
      <span class="mvs-toggle__label">{{ props.field.label }}</span>
    </label>
  </FieldWrapper>
</template>

<script setup lang="ts">
import FieldWrapper from './FieldWrapper.vue'
import type { FieldComponentProps } from '../../types'

const props = defineProps<FieldComponentProps>()

const onToggle = (event: Event) => {
  const target = event.target as HTMLInputElement
  props.onChange(target.checked)
}
</script>

// packages/react/src/components/fields/ToggleField.tsx
import React from 'react'
import type { FieldComponentProps } from '../../types'
import { FieldWrapper } from './FieldWrapper'

const ToggleField: React.FC<FieldComponentProps> = (props) => {
  return <CheckboxField {...props} />
}

const CheckboxField: React.FC<FieldComponentProps> = ({
  field,
  value,
  onChange,
  disabled,
  readonly,
  errors,
}) => {
  const checked = Boolean(value)
  return (
    <FieldWrapper field={field} value={value} onChange={onChange} disabled={disabled} readonly={readonly} errors={errors}>
      <label className="mfs-toggle">
        <input
          type="checkbox"
          checked={checked}
          onChange={(e) => onChange(e.target.checked)}
          disabled={disabled || readonly}
        />
        <span className="mfs-toggle__track">
          <span className="mfs-toggle__thumb" />
        </span>
        <span className="mfs-toggle__label">{field.label}</span>
      </label>
    </FieldWrapper>
  )
}

export default ToggleField
