// packages/react/src-legacy/components/list/ActionCell.tsx
/**
 * ActionCell - Row action buttons cell
 */

import React, { useState, useCallback, useRef, useEffect } from 'react'
import type { RowAction } from '@manifesto-ai/schema'

export interface ActionCellProps {
  rowId: string
  row: Record<string, unknown>
  actions: readonly RowAction[]
  onAction: (rowId: string, actionId: string, row: Record<string, unknown>) => void
  renderRowActions?: (row: Record<string, unknown>) => React.ReactNode
}

export const ActionCell: React.FC<ActionCellProps> = ({
  rowId,
  row,
  actions,
  onAction,
  renderRowActions,
}) => {
  const [isMenuOpen, setIsMenuOpen] = useState(false)
  const menuRef = useRef<HTMLDivElement>(null)

  // Custom render prop takes priority
  if (renderRowActions) {
    const customContent = renderRowActions(row)
    if (customContent !== null) {
      return (
        <td className="list-row__cell list-row__cell--actions">
          {customContent}
        </td>
      )
    }
  }

  // Close menu on outside click
  useEffect(() => {
    if (!isMenuOpen) return

    const handleClickOutside = (event: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(event.target as Node)) {
        setIsMenuOpen(false)
      }
    }

    document.addEventListener('mousedown', handleClickOutside)
    return () => document.removeEventListener('mousedown', handleClickOutside)
  }, [isMenuOpen])

  const handleActionClick = useCallback(
    (actionId: string) => {
      onAction(rowId, actionId, row)
      setIsMenuOpen(false)
    },
    [rowId, row, onAction]
  )

  const toggleMenu = useCallback(() => {
    setIsMenuOpen((prev) => !prev)
  }, [])

  // No actions
  if (!actions.length) {
    return <td className="list-row__cell list-row__cell--actions" />
  }

  // Inline mode for 1-2 actions
  if (actions.length <= 2) {
    return (
      <td className="list-row__cell list-row__cell--actions">
        <div className="list-action-cell list-action-cell--inline">
          {actions.map((action) => (
            <button
              key={action.id}
              type="button"
              className={`list-action-cell__btn list-action-cell__btn--${action.variant ?? 'ghost'}`}
              onClick={() => handleActionClick(action.id)}
              title={action.label}
            >
              {action.icon && (
                <span className="list-action-cell__icon">{action.icon}</span>
              )}
              <span className="list-action-cell__label">{action.label}</span>
            </button>
          ))}
        </div>
      </td>
    )
  }

  // Dropdown menu for 3+ actions
  return (
    <td className="list-row__cell list-row__cell--actions">
      <div className="list-action-cell list-action-cell--dropdown" ref={menuRef}>
        <button
          type="button"
          className="list-action-cell__trigger"
          onClick={toggleMenu}
          aria-expanded={isMenuOpen}
          aria-haspopup="menu"
        >
          <span className="list-action-cell__dots">{'\u22EE'}</span>
        </button>
        {isMenuOpen && (
          <div className="list-action-cell__menu" role="menu">
            {actions.map((action) => (
              <button
                key={action.id}
                type="button"
                role="menuitem"
                className={`list-action-cell__menu-item list-action-cell__menu-item--${action.variant ?? 'ghost'}`}
                onClick={() => handleActionClick(action.id)}
              >
                {action.icon && (
                  <span className="list-action-cell__icon">{action.icon}</span>
                )}
                <span className="list-action-cell__label">{action.label}</span>
              </button>
            ))}
          </div>
        )}
      </div>
    </td>
  )
}

export default ActionCell

// packages/vue/src-legacy/components/list/ActionCell.vue
<script setup lang="ts">
/**
 * ActionCell - 행 액션 버튼 셀
 */
import { ref, onMounted, onUnmounted } from 'vue'
import type { RowAction } from '@manifesto-ai/schema'

const props = defineProps<{
  rowId: string
  row: Record<string, unknown>
  actions: readonly RowAction[]
}>()

const emit = defineEmits<{
  action: [rowId: string, actionId: string, row: Record<string, unknown>]
}>()

const isMenuOpen = ref(false)
const menuRef = ref<HTMLDivElement | null>(null)

const handleActionClick = (actionId: string) => {
  emit('action', props.rowId, actionId, props.row)
  isMenuOpen.value = false
}

const toggleMenu = () => {
  isMenuOpen.value = !isMenuOpen.value
}

// Close menu on outside click
const handleClickOutside = (event: MouseEvent) => {
  if (menuRef.value && !menuRef.value.contains(event.target as Node)) {
    isMenuOpen.value = false
  }
}

onMounted(() => {
  document.addEventListener('mousedown', handleClickOutside)
})

onUnmounted(() => {
  document.removeEventListener('mousedown', handleClickOutside)
})
</script>

<template>
  <!-- No actions -->
  <td v-if="!actions.length" class="list-row__cell list-row__cell--actions" />

  <!-- Inline mode for 1-2 actions -->
  <td v-else-if="actions.length <= 2" class="list-row__cell list-row__cell--actions">
    <div class="list-action-cell list-action-cell--inline">
      <button
        v-for="action in actions"
        :key="action.id"
        type="button"
        :class="['list-action-cell__btn', `list-action-cell__btn--${action.variant ?? 'ghost'}`]"
        :title="action.label"
        @click="handleActionClick(action.id)"
      >
        <span v-if="action.icon" class="list-action-cell__icon">{{ action.icon }}</span>
        <span class="list-action-cell__label">{{ action.label }}</span>
      </button>
    </div>
  </td>

  <!-- Dropdown menu for 3+ actions -->
  <td v-else class="list-row__cell list-row__cell--actions">
    <div ref="menuRef" class="list-action-cell list-action-cell--dropdown">
      <button
        type="button"
        class="list-action-cell__trigger"
        :aria-expanded="isMenuOpen"
        aria-haspopup="menu"
        @click="toggleMenu"
      >
        <span class="list-action-cell__dots">&#8942;</span>
      </button>
      <div v-if="isMenuOpen" class="list-action-cell__menu" role="menu">
        <button
          v-for="action in actions"
          :key="action.id"
          type="button"
          role="menuitem"
          :class="[
            'list-action-cell__menu-item',
            `list-action-cell__menu-item--${action.variant ?? 'ghost'}`,
          ]"
          @click="handleActionClick(action.id)"
        >
          <span v-if="action.icon" class="list-action-cell__icon">{{ action.icon }}</span>
          <span class="list-action-cell__label">{{ action.label }}</span>
        </button>
      </div>
    </div>
  </td>
</template>
