// packages/react/src-legacy/components/list/ListToolbar.tsx
/**
 * ListToolbar - Search, filters, and bulk actions toolbar
 */

import React, { useState, useCallback, useRef, useEffect } from 'react'
import type { BulkAction, FilterConfig } from '@manifesto-ai/schema'

export interface ListToolbarProps {
  searchTerm: string
  filters: Readonly<Record<string, unknown>>
  filterConfig?: FilterConfig
  selectedCount: number
  bulkActions?: readonly BulkAction[]
  onSearch: (term: string) => void
  onFilter?: (fieldId: string, value: unknown) => void
  onResetFilters: () => void
  onBulkAction: (actionId: string) => void
  renderToolbar?: () => React.ReactNode
}

export const ListToolbar: React.FC<ListToolbarProps> = ({
  searchTerm,
  filters,
  filterConfig,
  selectedCount,
  bulkActions = [],
  onSearch,
  onFilter: _onFilter,
  onResetFilters,
  onBulkAction,
  renderToolbar,
}) => {
  // Note: _onFilter is available for future filter UI implementation
  void _onFilter
  // Custom render prop takes priority
  if (renderToolbar) {
    return <div className="list-toolbar">{renderToolbar()}</div>
  }

  const [localSearchTerm, setLocalSearchTerm] = useState(searchTerm)
  const searchDebounceRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  // Sync local search term with prop
  useEffect(() => {
    setLocalSearchTerm(searchTerm)
  }, [searchTerm])

  const handleSearchChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const value = e.target.value
      setLocalSearchTerm(value)

      // Debounce search
      if (searchDebounceRef.current) {
        clearTimeout(searchDebounceRef.current)
      }
      searchDebounceRef.current = setTimeout(() => {
        onSearch(value)
      }, 300)
    },
    [onSearch]
  )

  const handleSearchClear = useCallback(() => {
    setLocalSearchTerm('')
    onSearch('')
  }, [onSearch])

  const handleBulkActionClick = useCallback(
    (actionId: string) => {
      onBulkAction(actionId)
    },
    [onBulkAction]
  )

  const handleResetFilters = useCallback(() => {
    onResetFilters()
  }, [onResetFilters])

  // Check if search is enabled
  const searchEnabled = filterConfig?.searchable !== false

  // Check if any filters are active
  const hasActiveFilters = Object.keys(filters).length > 0 || searchTerm.length > 0

  // Filter bulk actions by min selection
  const availableBulkActions = bulkActions.filter((action) => {
    const minSelection = action.minSelection ?? 1
    return selectedCount >= minSelection
  })

  return (
    <div className="list-toolbar">
      {/* Left section: Search and filters */}
      <div className="list-toolbar__left">
        {/* Search input */}
        {searchEnabled && (
          <div className="list-toolbar__search">
            <input
              type="text"
              className="list-toolbar__search-input"
              placeholder={filterConfig?.searchPlaceholder ?? 'Search...'}
              value={localSearchTerm}
              onChange={handleSearchChange}
              aria-label="Search"
            />
            {localSearchTerm && (
              <button
                type="button"
                className="list-toolbar__search-clear"
                onClick={handleSearchClear}
                aria-label="Clear search"
              >
                {'\u2715'}
              </button>
            )}
          </div>
        )}

        {/* Reset filters button */}
        {hasActiveFilters && (
          <button
            type="button"
            className="list-toolbar__reset"
            onClick={handleResetFilters}
          >
            Reset filters
          </button>
        )}
      </div>

      {/* Right section: Bulk actions */}
      <div className="list-toolbar__right">
        {/* Selection info */}
        {selectedCount > 0 && (
          <span className="list-toolbar__selection-info">
            {selectedCount} selected
          </span>
        )}

        {/* Bulk action buttons */}
        {availableBulkActions.length > 0 && (
          <div className="list-toolbar__bulk-actions">
            {availableBulkActions.map((action) => (
              <button
                key={action.id}
                type="button"
                className={`list-toolbar__bulk-btn list-toolbar__bulk-btn--${action.variant ?? 'secondary'}`}
                data-action-id={action.id}
                onClick={() => handleBulkActionClick(action.id)}
              >
                {action.icon && (
                  <span className="list-toolbar__bulk-icon">{action.icon}</span>
                )}
                <span className="list-toolbar__bulk-label">{action.label}</span>
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}

export default ListToolbar

// packages/vue/src-legacy/components/list/ListToolbar.vue
<script setup lang="ts">
/**
 * ListToolbar - 검색, 필터, Bulk 액션 툴바
 */
import { ref, watch, computed, onUnmounted } from 'vue'
import type { BulkAction, FilterConfig } from '@manifesto-ai/schema'

const props = withDefaults(
  defineProps<{
    searchTerm: string
    filters: Readonly<Record<string, unknown>>
    filterConfig?: FilterConfig
    selectedCount: number
    bulkActions?: readonly BulkAction[]
  }>(),
  {
    filterConfig: undefined,
    bulkActions: () => [],
  }
)

const emit = defineEmits<{
  search: [term: string]
  filter: [fieldId: string, value: unknown]
  resetFilters: []
  bulkAction: [actionId: string]
}>()

const localSearchTerm = ref(props.searchTerm)
let searchDebounceTimer: ReturnType<typeof setTimeout> | null = null

// Sync local search term with prop
watch(
  () => props.searchTerm,
  (newValue) => {
    localSearchTerm.value = newValue
  }
)

const handleSearchChange = (e: Event) => {
  const target = e.target as HTMLInputElement
  const value = target.value
  localSearchTerm.value = value

  // Debounce search
  if (searchDebounceTimer) {
    clearTimeout(searchDebounceTimer)
  }
  searchDebounceTimer = setTimeout(() => {
    emit('search', value)
  }, 300)
}

const handleSearchClear = () => {
  localSearchTerm.value = ''
  emit('search', '')
}

const handleBulkActionClick = (actionId: string) => {
  emit('bulkAction', actionId)
}

const handleResetFilters = () => {
  emit('resetFilters')
}

// Computed
const searchEnabled = computed(() => props.filterConfig?.searchable !== false)

const hasActiveFilters = computed(
  () => Object.keys(props.filters).length > 0 || props.searchTerm.length > 0
)

const availableBulkActions = computed(() =>
  (props.bulkActions ?? []).filter((action) => {
    const minSelection = action.minSelection ?? 1
    return props.selectedCount >= minSelection
  })
)

onUnmounted(() => {
  if (searchDebounceTimer) {
    clearTimeout(searchDebounceTimer)
  }
})
</script>

<template>
  <div class="list-toolbar">
    <!-- Left section: Search and filters -->
    <div class="list-toolbar__left">
      <!-- Search input -->
      <div v-if="searchEnabled" class="list-toolbar__search">
        <input
          type="text"
          class="list-toolbar__search-input"
          :placeholder="filterConfig?.searchPlaceholder ?? 'Search...'"
          :value="localSearchTerm"
          aria-label="Search"
          @input="handleSearchChange"
        />
        <button
          v-if="localSearchTerm"
          type="button"
          class="list-toolbar__search-clear"
          aria-label="Clear search"
          @click="handleSearchClear"
        >
          &#10005;
        </button>
      </div>

      <!-- Reset filters button -->
      <button
        v-if="hasActiveFilters"
        type="button"
        class="list-toolbar__reset"
        @click="handleResetFilters"
      >
        Reset filters
      </button>
    </div>

    <!-- Right section: Bulk actions -->
    <div class="list-toolbar__right">
      <!-- Selection info -->
      <span v-if="selectedCount > 0" class="list-toolbar__selection-info">
        {{ selectedCount }} selected
      </span>

      <!-- Bulk action buttons -->
      <div v-if="availableBulkActions.length > 0" class="list-toolbar__bulk-actions">
        <button
          v-for="action in availableBulkActions"
          :key="action.id"
          type="button"
          :class="[
            'list-toolbar__bulk-btn',
            `list-toolbar__bulk-btn--${action.variant ?? 'secondary'}`,
          ]"
          :data-action-id="action.id"
          @click="handleBulkActionClick(action.id)"
        >
          <span v-if="action.icon" class="list-toolbar__bulk-icon">{{ action.icon }}</span>
          <span class="list-toolbar__bulk-label">{{ action.label }}</span>
        </button>
      </div>
    </div>
  </div>
</template>
