// packages/react/src/components/fields/AutocompleteField.tsx
import React from 'react'
import type { FieldComponentProps } from '../../types'
import { FieldWrapper } from './FieldWrapper'

const AutocompleteField: React.FC<FieldComponentProps> = (props) => {
  return <TextFallback {...props} />
}

const TextFallback: React.FC<FieldComponentProps> = ({
  field,
  value,
  onChange,
  disabled,
  readonly,
  errors,
}) => {
  return (
    <FieldWrapper field={field} value={value} onChange={onChange} disabled={disabled} readonly={readonly} errors={errors}>
      <input
        className="mfs-input"
        type="text"
        value={value === undefined || value === null ? '' : String(value)}
        placeholder={field.placeholder}
        onChange={(e) => onChange(e.target.value)}
        disabled={disabled}
        readOnly={readonly}
      />
    </FieldWrapper>
  )
}

export default AutocompleteField

// packages/vue/src/components/fields/AutocompleteField.vue
<template>
  <FieldWrapper v-bind="props">
    <input
      class="mvs-input"
      type="text"
      :value="stringValue"
      :placeholder="props.field.placeholder"
      :disabled="props.disabled"
      :readonly="props.readonly"
      @input="onInput"
    />
  </FieldWrapper>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import FieldWrapper from './FieldWrapper.vue'
import type { FieldComponentProps } from '../../types'

const props = defineProps<FieldComponentProps>()
const stringValue = computed(() => {
  const v = props.value
  return v === undefined || v === null ? '' : String(v)
})

const onInput = (event: Event) => {
  const target = event.target as HTMLInputElement
  props.onChange(target.value)
}
</script>
