// packages/react/src/components/fields/FieldWrapper.tsx
import React from 'react'
import type { FieldComponentProps } from '../../types'

interface FieldWrapperProps extends FieldComponentProps {
  children: React.ReactNode
}

export const FieldWrapper: React.FC<FieldWrapperProps> = ({
  field,
  errors,
  children,
}) => {
  return (
    <div className="mfs-field">
      {field.label && <div className="mfs-field__label">{field.label}</div>}
      {children}
      {field.helpText && <div className="mfs-field__help">{field.helpText}</div>}
      {errors.length > 0 && (
        <div className="mfs-field__errors">
          {errors.map((err, idx) => (
            <div key={idx} className="mfs-field__error">
              {err}
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

// packages/vue/src/components/fields/FieldWrapper.vue
<template>
  <div class="mvs-field">
    <div v-if="field.label" class="mvs-field__label">{{ field.label }}</div>
    <slot />
    <div v-if="field.helpText" class="mvs-field__help">{{ field.helpText }}</div>
    <div v-if="errors.length" class="mvs-field__errors">
      <div v-for="(err, idx) in errors" :key="idx" class="mvs-field__error">
        {{ err }}
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { FieldComponentProps } from '../../types'

defineProps<FieldComponentProps>()
</script>
