// packages/react/src/components/fields/FileField.tsx
import React from 'react'
import type { FieldComponentProps } from '../../types'
import { FieldWrapper } from './FieldWrapper'

const FileField: React.FC<FieldComponentProps> = ({
  field,
  onChange,
  disabled,
  readonly,
  errors,
  value,
}) => {
  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0] ?? null
    onChange(file)
  }

  return (
    <FieldWrapper field={field} value={value} onChange={onChange} disabled={disabled} readonly={readonly} errors={errors}>
      <input type="file" disabled={disabled || readonly} onChange={handleChange} />
      {typeof value === 'string' && <div className="mfs-file__name">{value}</div>}
    </FieldWrapper>
  )
}

export default FileField

// packages/vue/src/components/fields/FileField.vue
<template>
  <FieldWrapper v-bind="props">
    <input type="file" :disabled="props.disabled || props.readonly" @change="onChangeFile" />
    <div v-if="typeof props.value === 'string'" class="mvs-file__name">{{ props.value }}</div>
  </FieldWrapper>
</template>

<script setup lang="ts">
import FieldWrapper from './FieldWrapper.vue'
import type { FieldComponentProps } from '../../types'

const props = defineProps<FieldComponentProps>()

const onChangeFile = (event: Event) => {
  const target = event.target as HTMLInputElement
  const file = target.files?.[0] ?? null
  props.onChange(file)
}
</script>
