// packages/react/src/components/fields/ImageField.tsx
import React from 'react'
import type { FieldComponentProps } from '../../types'
import { FieldWrapper } from './FieldWrapper'

const ImageField: React.FC<FieldComponentProps> = ({
  field,
  onChange,
  disabled,
  readonly,
  errors,
  value,
}) => {
  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0] ?? null
    onChange(file)
  }

  const src = typeof value === 'string' ? value : undefined

  return (
    <FieldWrapper field={field} value={value} onChange={onChange} disabled={disabled} readonly={readonly} errors={errors}>
      <input type="file" accept="image/*" disabled={disabled || readonly} onChange={handleChange} />
      {src && <img src={src} alt={field.label ?? field.id} className="mfs-image__preview" />}
    </FieldWrapper>
  )
}

export default ImageField

// packages/vue/src/components/fields/ImageField.vue
<template>
  <FieldWrapper v-bind="props">
    <input type="file" accept="image/*" :disabled="props.disabled || props.readonly" @change="onChangeFile" />
    <img v-if="src" :src="src" :alt="props.field.label ?? props.field.id" class="mvs-image__preview" />
  </FieldWrapper>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import FieldWrapper from './FieldWrapper.vue'
import type { FieldComponentProps } from '../../types'

const props = defineProps<FieldComponentProps>()
const src = computed(() => (typeof props.value === 'string' ? props.value : undefined))

const onChangeFile = (event: Event) => {
  const target = event.target as HTMLInputElement
  const file = target.files?.[0] ?? null
  props.onChange(file)
}
</script>
