// apps/vue-example/src/components/manifesto-vuetify/RadioInput.vue
<script setup lang="ts">
/**
 * RadioInput - Vuetify v-radio-group wrapper
 */
import type { FieldComponentProps } from '@manifesto-ai/vue'
import { computed } from 'vue'

const props = defineProps<FieldComponentProps>()

const options = computed(() => props.field.state.options ?? [])
const hasError = computed(() => props.errors.length > 0)
const handleChange = (value: unknown) => props.onChange(value)
</script>

<template>
  <v-radio-group
    :id="props.field.fieldId"
    :model-value="props.value"
    @update:model-value="handleChange"
    :disabled="props.disabled"
    :readonly="props.readonly"
    :error="hasError"
  >
    <v-radio
      v-for="option in options"
      :key="option.value"
      :label="option.label"
      :value="option.value"
      :disabled="option.disabled"
    />
  </v-radio-group>
</template>

// packages/react/src-legacy/components/inputs/RadioInput.tsx
/**
 * RadioInput - Radio button group component
 */

import React from 'react'
import type { InputComponentProps } from '../../types/component'

export const RadioInput: React.FC<InputComponentProps> = ({
  fieldId,
  value,
  onChange,
  disabled = false,
  readonly = false,
  componentProps = {},
  hasError = false,
  options = [],
  onFocus,
  onBlur,
}) => {
  const handleChange = (optionValue: string | number) => {
    if (!readonly) {
      onChange(optionValue)
    }
  }

  const { direction = 'vertical', ...restProps } = componentProps as { direction?: 'horizontal' | 'vertical' }

  return (
    <div
      className={`input-radio ${direction === 'horizontal' ? 'input-radio--horizontal' : ''} ${hasError ? 'input-radio--error' : ''}`}
      role="radiogroup"
      {...restProps}
    >
      {options.map((option) => (
        <label
          key={option.value}
          className={`input-radio__option ${option.disabled || disabled ? 'input-radio__option--disabled' : ''}`}
        >
          <input
            type="radio"
            name={fieldId}
            value={option.value}
            checked={value === option.value}
            disabled={option.disabled || disabled}
            className="input-radio__input"
            onChange={() => handleChange(option.value)}
            onFocus={onFocus}
            onBlur={onBlur}
          />
          <span className="input-radio__label">{option.label}</span>
        </label>
      ))}
    </div>
  )
}

export default RadioInput
