// apps/vue-example/src/components/manifesto-vuetify/SelectInput.vue
<script setup lang="ts">
/**
 * SelectInput - Vuetify v-select wrapper
 */
import type { FieldComponentProps } from '@manifesto-ai/vue'
import { computed } from 'vue'

const props = defineProps<FieldComponentProps>()

const options = computed(() => props.field.state.options ?? [])
const hasError = computed(() => props.errors.length > 0)
const handleChange = (value: unknown) => props.onChange(value)
</script>

<template>
  <v-select
    :id="props.field.fieldId"
    :model-value="props.value"
    @update:model-value="handleChange"
    :items="options"
    item-title="label"
    item-value="value"
    :disabled="props.disabled"
    :readonly="props.readonly"
    :placeholder="props.field.placeholder"
    :error="hasError"
  />
</template>

// packages/react/src-legacy/components/inputs/SelectInput.tsx
/**
 * SelectInput - Single select component
 */

import React from 'react'
import type { InputComponentProps } from '../../types/component'

export const SelectInput: React.FC<InputComponentProps> = ({
  fieldId,
  value,
  onChange,
  disabled = false,
  readonly = false,
  placeholder,
  componentProps = {},
  hasError = false,
  options = [],
  onFocus,
  onBlur,
}) => {
  const handleChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const val = e.target.value
    onChange(val === '' ? null : val)
  }

  return (
    <select
      id={fieldId}
      value={(value as string | number) ?? ''}
      disabled={disabled || readonly}
      className={`input-select ${hasError ? 'input-select--error' : ''} ${disabled ? 'input-select--disabled' : ''}`}
      onChange={handleChange}
      onFocus={onFocus}
      onBlur={onBlur}
      {...componentProps}
    >
      {placeholder && (
        <option value="" disabled>
          {placeholder}
        </option>
      )}
      {options.map((option) => (
        <option key={option.value} value={option.value} disabled={option.disabled}>
          {option.label}
        </option>
      ))}
    </select>
  )
}

export default SelectInput
