// apps/vue-example/src/components/manifesto-vuetify/SliderInput.vue
<script setup lang="ts">
/**
 * SliderInput - Vuetify v-slider wrapper
 */
import type { FieldComponentProps } from '@manifesto-ai/vue'
import { computed } from 'vue'

const props = defineProps<FieldComponentProps>()

const hasError = computed(() => props.errors.length > 0)
const fieldProps = computed(() => props.field.state.props ?? {})
const min = computed(() => (fieldProps.value.min as number) ?? 0)
const max = computed(() => (fieldProps.value.max as number) ?? 100)
const step = computed(() => (fieldProps.value.step as number) ?? 1)
const showValue = computed(() => (fieldProps.value.showValue as boolean) ?? true)
const handleChange = (value: unknown) => props.onChange(value)
</script>

<template>
  <v-slider
    :id="props.field.fieldId"
    :model-value="props.value as number"
    @update:model-value="handleChange"
    :disabled="props.disabled"
    :readonly="props.readonly"
    :error="hasError"
    :min="min"
    :max="max"
    :step="step"
    :thumb-label="showValue ? 'always' : false"
    color="primary"
  />
</template>

// packages/react/src-legacy/components/inputs/SliderInput.tsx
/**
 * SliderInput - Slider/range input component
 */

import React from 'react'
import type { InputComponentProps } from '../../types/component'

export const SliderInput: React.FC<InputComponentProps> = ({
  fieldId,
  value,
  onChange,
  disabled = false,
  readonly = false,
  componentProps = {},
  hasError = false,
  onFocus,
  onBlur,
}) => {
  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    onChange(Number(e.target.value))
  }

  const { min = 0, max = 100, step = 1, showValue = true, ...restProps } = componentProps as {
    min?: number
    max?: number
    step?: number
    showValue?: boolean
  }

  return (
    <div className={`input-slider ${hasError ? 'input-slider--error' : ''} ${disabled ? 'input-slider--disabled' : ''}`}>
      <input
        type="range"
        id={fieldId}
        value={(value as number) ?? min}
        disabled={disabled}
        readOnly={readonly}
        min={min}
        max={max}
        step={step}
        className="input-slider__input"
        onChange={handleChange}
        onFocus={onFocus}
        onBlur={onBlur}
        {...restProps}
      />
      {showValue && <span className="input-slider__value">{(value as number) ?? min}</span>}
    </div>
  )
}

export default SliderInput
