// apps/vue-example/src/components/manifesto-vuetify/TextareaInput.vue
<script setup lang="ts">
/**
 * TextareaInput - Vuetify v-textarea wrapper
 */
import type { FieldComponentProps } from '@manifesto-ai/vue'
import { computed } from 'vue'

const props = defineProps<FieldComponentProps>()

const hasError = computed(() => props.errors.length > 0)
const fieldProps = computed(() => props.field.state.props ?? {})
const rows = computed(() => (fieldProps.value.rows as number) ?? 3)
const handleChange = (value: unknown) => props.onChange(value)
</script>

<template>
  <v-textarea
    :id="props.field.fieldId"
    :model-value="props.value"
    @update:model-value="handleChange"
    :disabled="props.disabled"
    :readonly="props.readonly"
    :placeholder="props.field.placeholder"
    :error="hasError"
    :rows="rows"
  />
</template>

// packages/react/src-legacy/components/inputs/TextareaInput.tsx
/**
 * TextareaInput - Textarea input component
 */

import React from 'react'
import type { InputComponentProps } from '../../types/component'

export const TextareaInput: React.FC<InputComponentProps> = ({
  fieldId,
  value,
  onChange,
  disabled = false,
  readonly = false,
  placeholder,
  componentProps = {},
  hasError = false,
  onFocus,
  onBlur,
}) => {
  const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    onChange(e.target.value)
  }

  const { rows = 4, ...restProps } = componentProps as { rows?: number }

  return (
    <textarea
      id={fieldId}
      value={(value as string) ?? ''}
      disabled={disabled}
      readOnly={readonly}
      placeholder={placeholder}
      rows={rows}
      className={`input-textarea ${hasError ? 'input-textarea--error' : ''} ${disabled ? 'input-textarea--disabled' : ''}`}
      onChange={handleChange}
      onFocus={onFocus}
      onBlur={onBlur}
      {...restProps}
    />
  )
}

export default TextareaInput
