// apps/vue-example/src/components/manifesto-vuetify/ToggleInput.vue
<script setup lang="ts">
/**
 * ToggleInput - Vuetify v-switch wrapper
 */
import type { FieldComponentProps } from '@manifesto-ai/vue'
import { computed } from 'vue'

const props = defineProps<FieldComponentProps>()

const hasError = computed(() => props.errors.length > 0)
const fieldProps = computed(() => props.field.state.props ?? {})
const label = computed(() => (fieldProps.value.label as string) || props.field.label)
const handleChange = (value: unknown) => props.onChange(value ?? false)
</script>

<template>
  <v-switch
    :id="props.field.fieldId"
    :model-value="props.value"
    @update:model-value="handleChange"
    :disabled="props.disabled"
    :readonly="props.readonly"
    :error="hasError"
    :label="label"
    color="primary"
  />
</template>

// packages/react/src-legacy/components/inputs/ToggleInput.tsx
/**
 * ToggleInput - Toggle/switch input component
 */

import React from 'react'
import type { InputComponentProps } from '../../types/component'

export const ToggleInput: React.FC<InputComponentProps> = ({
  fieldId,
  value,
  onChange,
  disabled = false,
  readonly = false,
  componentProps = {},
  hasError = false,
  onFocus,
  onBlur,
}) => {
  const handleChange = () => {
    if (!readonly && !disabled) {
      onChange(!value)
    }
  }

  const { label, ...restProps } = componentProps as { label?: string }

  return (
    <label
      className={`input-toggle ${hasError ? 'input-toggle--error' : ''} ${disabled ? 'input-toggle--disabled' : ''}`}
    >
      <button
        type="button"
        id={fieldId}
        role="switch"
        aria-checked={Boolean(value)}
        disabled={disabled}
        className={`input-toggle__switch ${value ? 'input-toggle__switch--on' : ''}`}
        onClick={handleChange}
        onFocus={onFocus}
        onBlur={onBlur}
        {...restProps}
      >
        <span className="input-toggle__thumb" />
      </button>
      {label && <span className="input-toggle__label">{label}</span>}
    </label>
  )
}

export default ToggleInput
