// apps/vue-example/src/components/manifesto-vuetify/NumberInput.vue
<script setup lang="ts">
/**
 * NumberInput - Vuetify v-text-field type=number wrapper
 */
import type { FieldComponentProps } from '@manifesto-ai/vue'
import { computed } from 'vue'

const props = defineProps<FieldComponentProps>()

const hasError = computed(() => props.errors.length > 0)
const handleUpdate = (value: string | number | null) => {
  if (value === '' || value === null) {
    props.onChange(null)
  } else {
    props.onChange(Number(value))
  }
}
</script>

<template>
  <v-text-field
    :id="props.field.fieldId"
    type="number"
    :model-value="props.value"
    @update:model-value="handleUpdate"
    :disabled="props.disabled"
    :readonly="props.readonly"
    :placeholder="props.field.placeholder"
    :error="hasError"
  />
</template>

// apps/react-example/src/components/manifesto-shadcn/NumberInput.tsx
import type { FieldComponentProps } from '@manifesto-ai/react'
import { Input } from '@/components/ui/input'
import { cn } from '@/lib/utils'

export default function NumberInput({
  field,
  value,
  onChange,
  disabled,
  readonly,
  errors,
}: FieldComponentProps) {
  const hasError = errors.length > 0
  const props = field.state.props ?? {}
  const min = props.min as number | undefined
  const max = props.max as number | undefined
  const step = props.step as number | undefined

  return (
    <Input
      type="number"
      id={field.fieldId}
      value={value != null ? String(value) : ''}
      onChange={(e) => {
        const val = e.target.value
        onChange(val === '' ? null : Number(val))
      }}
      disabled={disabled}
      readOnly={readonly}
      placeholder={field.placeholder}
      min={min}
      max={max}
      step={step}
      aria-invalid={hasError}
      className={cn(hasError && 'border-destructive')}
    />
  )
}
