// apps/vue-example/src/components/manifesto-vuetify/RadioInput.vue
<script setup lang="ts">
/**
 * RadioInput - Vuetify v-radio-group wrapper
 */
import type { FieldComponentProps } from '@manifesto-ai/vue'
import { computed } from 'vue'

const props = defineProps<FieldComponentProps>()

const options = computed(() => props.field.state.options ?? [])
const hasError = computed(() => props.errors.length > 0)
const handleChange = (value: unknown) => props.onChange(value)
</script>

<template>
  <v-radio-group
    :id="props.field.fieldId"
    :model-value="props.value"
    @update:model-value="handleChange"
    :disabled="props.disabled"
    :readonly="props.readonly"
    :error="hasError"
  >
    <v-radio
      v-for="option in options"
      :key="option.value"
      :label="option.label"
      :value="option.value"
      :disabled="option.disabled"
    />
  </v-radio-group>
</template>

// apps/react-example/src/components/manifesto-shadcn/RadioInput.tsx
import type { FieldComponentProps } from '@manifesto-ai/react'
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'
import { Label } from '@/components/ui/label'

export default function RadioInput({
  field,
  value,
  onChange,
  disabled,
}: FieldComponentProps) {
  const options = field.state.options ?? []

  return (
    <RadioGroup
      value={value != null ? String(value) : undefined}
      onValueChange={onChange}
      disabled={disabled}
    >
      {options.map((opt: { value: string | number; label: string; disabled?: boolean }) => (
        <div key={String(opt.value)} className="flex items-center gap-2">
          <RadioGroupItem
            value={String(opt.value)}
            id={`${field.fieldId}-${opt.value}`}
            disabled={opt.disabled}
          />
          <Label
            htmlFor={`${field.fieldId}-${opt.value}`}
            className="cursor-pointer font-normal"
          >
            {opt.label}
          </Label>
        </div>
      ))}
    </RadioGroup>
  )
}
