// apps/vue-example/src/components/manifesto-vuetify/SelectInput.vue
<script setup lang="ts">
/**
 * SelectInput - Vuetify v-select wrapper
 */
import type { FieldComponentProps } from '@manifesto-ai/vue'
import { computed } from 'vue'

const props = defineProps<FieldComponentProps>()

const options = computed(() => props.field.state.options ?? [])
const hasError = computed(() => props.errors.length > 0)
const handleChange = (value: unknown) => props.onChange(value)
</script>

<template>
  <v-select
    :id="props.field.fieldId"
    :model-value="props.value"
    @update:model-value="handleChange"
    :items="options"
    item-title="label"
    item-value="value"
    :disabled="props.disabled"
    :readonly="props.readonly"
    :placeholder="props.field.placeholder"
    :error="hasError"
  />
</template>

// apps/react-example/src/components/manifesto-shadcn/SelectInput.tsx
import type { FieldComponentProps } from '@manifesto-ai/react'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { cn } from '@/lib/utils'

export default function SelectInput({
  field,
  value,
  onChange,
  disabled,
  errors,
}: FieldComponentProps) {
  const hasError = errors.length > 0
  const options = field.state.options ?? []

  return (
    <Select
      value={value != null ? String(value) : undefined}
      onValueChange={onChange}
      disabled={disabled}
    >
      <SelectTrigger
        id={field.fieldId}
        className={cn(hasError && 'border-destructive')}
        aria-invalid={hasError}
      >
        <SelectValue placeholder={field.placeholder ?? 'Select an option'} />
      </SelectTrigger>
      <SelectContent>
        {options.map((opt: { value: string | number; label: string; disabled?: boolean }) => (
          <SelectItem
            key={String(opt.value)}
            value={String(opt.value)}
            disabled={opt.disabled}
          >
            {opt.label}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  )
}
