// apps/vue-example/src/components/manifesto-vuetify/TextareaInput.vue
<script setup lang="ts">
/**
 * TextareaInput - Vuetify v-textarea wrapper
 */
import type { FieldComponentProps } from '@manifesto-ai/vue'
import { computed } from 'vue'

const props = defineProps<FieldComponentProps>()

const hasError = computed(() => props.errors.length > 0)
const fieldProps = computed(() => props.field.state.props ?? {})
const rows = computed(() => (fieldProps.value.rows as number) ?? 3)
const handleChange = (value: unknown) => props.onChange(value)
</script>

<template>
  <v-textarea
    :id="props.field.fieldId"
    :model-value="props.value"
    @update:model-value="handleChange"
    :disabled="props.disabled"
    :readonly="props.readonly"
    :placeholder="props.field.placeholder"
    :error="hasError"
    :rows="rows"
  />
</template>

// apps/react-example/src/components/manifesto-shadcn/TextareaInput.tsx
import type { FieldComponentProps } from '@manifesto-ai/react'
import { Textarea } from '@/components/ui/textarea'
import { cn } from '@/lib/utils'

export default function TextareaInput({
  field,
  value,
  onChange,
  disabled,
  readonly,
  errors,
}: FieldComponentProps) {
  const hasError = errors.length > 0
  const props = field.state.props ?? {}
  const rows = (props.rows as number) ?? 4

  return (
    <Textarea
      id={field.fieldId}
      value={(value as string) ?? ''}
      onChange={(e) => onChange(e.target.value)}
      disabled={disabled}
      readOnly={readonly}
      placeholder={field.placeholder}
      rows={rows}
      aria-invalid={hasError}
      className={cn(hasError && 'border-destructive')}
    />
  )
}
