// apps/vue-example/src/components/manifesto-vuetify/TextInput.vue
<script setup lang="ts">
/**
 * TextInput - Vuetify v-text-field wrapper
 */
import type { FieldComponentProps } from '@manifesto-ai/vue'
import { computed } from 'vue'

const props = defineProps<FieldComponentProps>()

const hasError = computed(() => props.errors.length > 0)
const handleChange = (value: unknown) => props.onChange(value)
</script>

<template>
  <v-text-field
    :id="props.field.fieldId"
    :model-value="props.value"
    @update:model-value="handleChange"
    :disabled="props.disabled"
    :readonly="props.readonly"
    :placeholder="props.field.placeholder"
    :error="hasError"
  />
</template>

// apps/react-example/src/components/manifesto-shadcn/TextInput.tsx
import type { FieldComponentProps } from '@manifesto-ai/react'
import { Input } from '@/components/ui/input'
import { cn } from '@/lib/utils'

export default function TextInput({
  field,
  value,
  onChange,
  disabled,
  readonly,
  errors,
}: FieldComponentProps) {
  const hasError = errors.length > 0
  return (
    <Input
      id={field.fieldId}
      value={(value as string) ?? ''}
      onChange={(e) => onChange(e.target.value)}
      disabled={disabled}
      readOnly={readonly}
      placeholder={field.placeholder}
      aria-invalid={hasError}
      className={cn(hasError && 'border-destructive')}
    />
  )
}
