// packages/vue/src-legacy/components/list/EmptyState.vue
<script setup lang="ts">
/**
 * EmptyState - 빈 상태 표시 컴포넌트
 */
import type { EmptyStateConfig } from '@manifesto-ai/schema'

const props = withDefaults(
  defineProps<{
    config?: EmptyStateConfig
  }>(),
  {
    config: undefined,
  }
)

const emit = defineEmits<{
  action: []
}>()

const title = computed(() => props.config?.title ?? 'No data')
const description = computed(() => props.config?.description)
const icon = computed(() => props.config?.icon)
const actionLabel = computed(() => props.config?.action?.label)
</script>

<script lang="ts">
import { computed } from 'vue'
</script>

<template>
  <div class="list-empty-state">
    <div v-if="icon" class="list-empty-state__icon">
      <span>{{ icon }}</span>
    </div>
    <div class="list-empty-state__content">
      <h3 class="list-empty-state__title">{{ title }}</h3>
      <p v-if="description" class="list-empty-state__description">{{ description }}</p>
    </div>
    <button
      v-if="actionLabel"
      type="button"
      class="list-empty-state__action"
      @click="emit('action')"
    >
      {{ actionLabel }}
    </button>
  </div>
</template>

// packages/react/src-legacy/components/list/EmptyState.tsx
/**
 * EmptyState - Empty state display for lists
 */

import React from 'react'
import type { EmptyStateConfig } from '@manifesto-ai/schema'

export interface EmptyStateProps {
  config?: EmptyStateConfig
  onAction?: () => void
}

export const EmptyState: React.FC<EmptyStateProps> = ({ config, onAction }) => {
  const title = config?.title ?? 'No data'
  const description = config?.description
  const icon = config?.icon
  const actionLabel = config?.action?.label

  return (
    <div className="list-empty-state">
      {icon && (
        <div className="list-empty-state__icon">
          <span>{icon}</span>
        </div>
      )}
      <div className="list-empty-state__content">
        <h3 className="list-empty-state__title">{title}</h3>
        {description && (
          <p className="list-empty-state__description">{description}</p>
        )}
      </div>
      {actionLabel && onAction && (
        <button
          type="button"
          className="list-empty-state__action"
          onClick={onAction}
        >
          {actionLabel}
        </button>
      )}
    </div>
  )
}

export default EmptyState
